import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `src/vendor/**` is a verbatim copy of a published package (see its README):
  // linting it would enforce THIS repo's house rules on someone else's file, and
  // the whole value of the copy is that it is byte-identical to what npm ships —
  // `diff` answers "has it drifted?" only while nothing here has been adapted.
  // It passes its own repo's lint; it is not ours to restyle.
  globalIgnores(['dist', 'src/vendor']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  {
    // R6: every literal has one home. External URLs and platform paths are
    // spelled once — in src/lib/urls.ts (external) and src/lib/routes.ts +
    // src/lib/launch.ts (platform path builders) — and imported everywhere
    // else, so a moved install flow is one edit rather than a grep.
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Literal[value=/^https?:\\/\\//]',
          message: "External URLs live in src/lib/urls.ts — import them, don't spell them.",
        },
        {
          selector: 'TemplateLiteral[quasis.0.value.raw=/^https?:\\/\\//]',
          message: "External URLs live in src/lib/urls.ts — import them, don't spell them.",
        },
        {
          selector: 'Literal[value=/^\\/(present|edit|home)(\\/|$)/]',
          message: "Platform paths live in src/lib/routes.ts builders — import them, don't spell them.",
        },
        {
          selector: 'TemplateLiteral[quasis.0.value.raw=/^\\/(present|edit|home)(\\/|$)/]',
          message: "Platform paths live in src/lib/routes.ts builders — import them, don't spell them.",
        },
      ],
    },
  },
  {
    // The one homes themselves; the generated corpus index (llms.txt content,
    // regenerated by check-corpora); and tests, where URLs are inputs.
    files: [
      'src/lib/routes.ts',
      'src/lib/urls.ts',
      'src/lib/launch.ts',
      'src/data/corpusIndex.ts',
      'src/**/*.test.{ts,tsx}',
    ],
    rules: { 'no-restricted-syntax': 'off' },
  },
])
