// GENERATED by scripts/check-corpora.mjs — do not edit.
//
// The frontmatter of every entry in every declared corpus, validated against the schema its
// corpus marker declares, plus the compiled MDX component for each. One authored source (the
// MDX file), one generated artifact, and the generator IS the validator — so the index can
// never describe an entry the checker did not pass.

import type { ComponentType } from 'react';
import Entry0 from '../../docs/capabilities--identity.mdx';
import Entry1 from '../../docs/capabilities--model.mdx';
import Entry2 from '../../docs/sdk--entry.mdx';
import Entry3 from '../../docs/start--overview.mdx';
import Entry4 from '../../tutorials/bind-a-space.mdx';
import Entry5 from '../../tutorials/local-claude-code.mdx';
import Entry6 from '../../tutorials/your-first-app.mdx';

export interface CorpusHeading {
  /** 2 or 3 — the markdown level. */
  depth: number;
  text: string;
  /** The id remarkHeadingAnchors renders, computed by the SAME headingId(). */
  id: string;
}

export interface CorpusEntry {
  /** Repo-relative path of the entry. */
  path: string;
  /** Filename without the extension — the URL segment. */
  slug: string;
  frontmatter: Record<string, string | number | boolean | string[]>;
  /** The entry's headings, for a table of contents and step navigation. */
  headings: CorpusHeading[];
}

export const CORPUS_INDEX: CorpusEntry[] = [
  {
    "path": "docs/capabilities--identity.mdx",
    "slug": "capabilities--identity",
    "frontmatter": {
      "title": "Identity and sign-in.",
      "lead": "Identity is a capability like any other. You get a stable, opaque handle for the signed-in user — never a token, never an email, never a secret.",
      "group": "capabilities",
      "groupLabel": "Capabilities",
      "order": 40
    },
    "headings": [
      {
        "depth": 2,
        "text": "Reacting to session changes.",
        "id": "reacting-to-session-changes"
      }
    ]
  },
  {
    "path": "docs/capabilities--model.mdx",
    "slug": "capabilities--model",
    "frontmatter": {
      "title": "The consent model.",
      "lead": "Access to data is asked for, not taken. The filesystem you see is the filesystem you got. Every privileged call replies with a typed result, and forbidden means policy — not a bug to retry around.",
      "group": "capabilities",
      "groupLabel": "Capabilities",
      "order": 30
    },
    "headings": [
      {
        "depth": 2,
        "text": "Requesting more access.",
        "id": "requesting-more-access"
      },
      {
        "depth": 2,
        "text": "Typed errors everywhere.",
        "id": "typed-errors-everywhere"
      }
    ]
  },
  {
    "path": "docs/sdk--entry.mdx",
    "slug": "sdk--entry",
    "frontmatter": {
      "title": "The SDK entry point.",
      "lead": "All platform interaction goes through @immediately-run/sdk — the only channel between your sandboxed app and the host. Pin it, import it, and call protocol methods reactively.",
      "group": "sdk",
      "groupLabel": "SDK",
      "order": 20
    },
    "headings": [
      {
        "depth": 2,
        "text": "Install and import.",
        "id": "install-and-import"
      },
      {
        "depth": 2,
        "text": "Protocol and versioning.",
        "id": "protocol-and-versioning"
      }
    ]
  },
  {
    "path": "docs/start--overview.mdx",
    "slug": "start--overview",
    "frontmatter": {
      "title": "Run any app from its source.",
      "lead": "immediately.run loads a React + TypeScript app straight from a GitHub repo and transpiles it in the browser — no server, no deploy step. Open it, use it, then pop the hood.",
      "group": "start",
      "groupLabel": "Getting started",
      "order": 10
    },
    "headings": [
      {
        "depth": 2,
        "text": "The run, edit, contribute loop.",
        "id": "the-run-edit-contribute-loop"
      },
      {
        "depth": 2,
        "text": "Where to go next.",
        "id": "where-to-go-next"
      }
    ]
  },
  {
    "path": "tutorials/bind-a-space.mdx",
    "slug": "bind-a-space",
    "frontmatter": {
      "title": "Give a fork a folder to work in.",
      "num": "03",
      "pillar": "SPACES",
      "outcome": "A forked app bound to a folder it can read and write, by your consent.",
      "prereqs": "A fork of an app and a space or folder to bind it to.",
      "time": "10 min",
      "difficulty": "Intermediate",
      "tags": [
        "spaces",
        "capabilities",
        "consent"
      ],
      "order": 30,
      "nextSlug": "your-first-app",
      "nextLabel": "Publish an app by pushing a repo."
    },
    "headings": [
      {
        "depth": 3,
        "text": "Fork the app.",
        "id": "fork-the-app"
      },
      {
        "depth": 3,
        "text": "Request a folder.",
        "id": "request-a-folder"
      },
      {
        "depth": 3,
        "text": "Grant access in the host prompt.",
        "id": "grant-access-in-the-host-prompt"
      },
      {
        "depth": 3,
        "text": "Read and write through the mount.",
        "id": "read-and-write-through-the-mount"
      }
    ]
  },
  {
    "path": "tutorials/local-claude-code.mdx",
    "slug": "local-claude-code",
    "frontmatter": {
      "title": "Change an app by asking a coding agent.",
      "num": "02",
      "pillar": "AGENTS",
      "outcome": "An app feature written by a local coding agent, then run from source.",
      "prereqs": "An app repo cloned locally and a coding agent installed.",
      "time": "12 min",
      "difficulty": "Intermediate",
      "tags": [
        "agents",
        "local-dev",
        "forking"
      ],
      "order": 20,
      "nextSlug": "bind-a-space",
      "nextLabel": "Give a fork a folder to work in."
    },
    "headings": [
      {
        "depth": 3,
        "text": "Clone an app you want to change.",
        "id": "clone-an-app-you-want-to-change"
      },
      {
        "depth": 3,
        "text": "Ask the agent for the change.",
        "id": "ask-the-agent-for-the-change"
      },
      {
        "depth": 3,
        "text": "Run it against your working tree.",
        "id": "run-it-against-your-working-tree"
      },
      {
        "depth": 3,
        "text": "Push the agent’s work.",
        "id": "push-the-agents-work"
      }
    ]
  },
  {
    "path": "tutorials/your-first-app.mdx",
    "slug": "your-first-app",
    "frontmatter": {
      "title": "Publish an app by pushing a repo.",
      "num": "01",
      "pillar": "PUBLISHING",
      "outcome": "A live app, running from your GitHub repo. No deploy step.",
      "prereqs": "A GitHub account and a repo you can push to.",
      "time": "8 min",
      "difficulty": "Beginner",
      "tags": [
        "publishing",
        "github",
        "no-deploy"
      ],
      "order": 10,
      "nextSlug": "local-claude-code",
      "nextLabel": "Change an app by asking a coding agent."
    },
    "headings": [
      {
        "depth": 3,
        "text": "Start from the template.",
        "id": "start-from-the-template"
      },
      {
        "depth": 3,
        "text": "Make it yours in App.tsx.",
        "id": "make-it-yours-in-apptsx"
      },
      {
        "depth": 3,
        "text": "Push to GitHub.",
        "id": "push-to-github"
      },
      {
        "depth": 3,
        "text": "Run it live.",
        "id": "run-it-live"
      }
    ]
  }
];

/** Path → the compiled MDX component. Rendered inside an <MDXProvider>-style component map
 *  so the corpus's custom components (<Callout/>, <ApiSignature/>, …) resolve. */
export const CORPUS_ENTRIES: Record<string, ComponentType<Record<string, unknown>>> = {
  "docs/capabilities--identity.mdx": Entry0,
  "docs/capabilities--model.mdx": Entry1,
  "docs/sdk--entry.mdx": Entry2,
  "docs/start--overview.mdx": Entry3,
  "tutorials/bind-a-space.mdx": Entry4,
  "tutorials/local-claude-code.mdx": Entry5,
  "tutorials/your-first-app.mdx": Entry6,
};

/** The entries of one corpus, in declared `order`. */
export function corpusEntries(dir: string): CorpusEntry[] {
  return CORPUS_INDEX.filter((e) => e.path.startsWith(`${dir}/`)).sort(
    (a, b) => Number(a.frontmatter.order ?? 0) - Number(b.frontmatter.order ?? 0),
  );
}

/** The machine surface, byte-identical to `public/llms.txt`. Exported so the page's
 *  Copy button hands over exactly what the file contains. */
export const LLMS_TXT = "# immediately.run\n> Apps you can take apart. Run any React/TS app from its source, in the browser. Fork and contribute back from the page itself.\n\n## Getting started\n- [Run any app from its source](/docs/start/overview): immediately.run loads a React + TypeScript app straight from a GitHub repo and transpiles it in the browser — no server, no deploy step. Open it, use it, then pop the hood. (source: docs/start--overview.mdx)\n\n## SDK\n- [The SDK entry point](/docs/sdk/entry): All platform interaction goes through @immediately-run/sdk — the only channel between your sandboxed app and the host. Pin it, import it, and call protocol methods reactively. (source: docs/sdk--entry.mdx)\n\n## Capabilities\n- [The consent model](/docs/capabilities/model): Access to data is asked for, not taken. The filesystem you see is the filesystem you got. Every privileged call replies with a typed result, and forbidden means policy — not a bug to retry around. (source: docs/capabilities--model.mdx)\n- [Identity and sign-in](/docs/capabilities/identity): Identity is a capability like any other. You get a stable, opaque handle for the signed-in user — never a token, never an email, never a secret. (source: docs/capabilities--identity.mdx)\n";
